type Item {
  id: ID!
  title: String!
  description: String
}

type Query {
  items: [Item]!
  item(id: Int!): Item!
}

input ItemInput {
  title: String!
  description: String
}

type Mutation {
  createItem(input: ItemInput!): Item!
}
