type Item {
  id: ID!
  title: String!
  description: String
}

type Query {
  items: [Item]!
  item(id: Int!): Item!
}

input CreateItemInput {
  """
  Item title
  """
  title: String!
  """
  Item description
  """
  description: String
}

input RemoveItemInput {
  id: ID!
}

type Mutation {
  createItem(input: CreateItemInput!): Item!
  removeItem(input: RemoveItemInput): Boolean!
}
